# Define final image
FROM ubuntu:20.04
LABEL org.opencontainers.image.source https://github.com/onnovalkering/brane

# Update the mirrors
RUN echo "deb mirror://mirrors.ubuntu.com/mirrors.txt $(. /etc/os-release && echo $VERSION_CODENAME) main restricted universe multiverse" > /etc/apt/sources.list && \
    echo "deb mirror://mirrors.ubuntu.com/mirrors.txt $(. /etc/os-release && echo $VERSION_CODENAME)-updates main restricted universe multiverse" >> /etc/apt/sources.list && \
    echo "deb mirror://mirrors.ubuntu.com/mirrors.txt $(. /etc/os-release && echo $VERSION_CODENAME)-security main restricted universe multiverse" >> /etc/apt/sources.list

# Install the package dependencies
RUN apt-get update && apt-get install -y \
    gnupg2 \
    libssl1.1 \
    wget \
 && rm -rf /var/lib/apt/lists/*

# Install something else?
RUN . /etc/os-release \
 && sh -c "echo 'deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/x${NAME}_${VERSION_ID}/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list" \
 && wget -nv https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/x${NAME}_${VERSION_ID}/Release.key -O- | apt-key add - \
 && apt-get update \
 && apt-get install -y skopeo \
 && rm -rf /var/lib/apt/lists/*

# Copy the start wrapper script
COPY ./contrib/scripts/container-start.sh /start.sh
RUN chmod +x /start.sh

# Create the build directory
RUN mkdir /build

# Run the build script
ENTRYPOINT [ "/start.sh", "brane-api" ]
