# Define the image
FROM ubuntu:20.04

# Update the mirrors
RUN echo "deb mirror://mirrors.ubuntu.com/mirrors.txt $(. /etc/os-release && echo $VERSION_CODENAME) main restricted universe multiverse" > /etc/apt/sources.list && \
    echo "deb mirror://mirrors.ubuntu.com/mirrors.txt $(. /etc/os-release && echo $VERSION_CODENAME)-updates main restricted universe multiverse" >> /etc/apt/sources.list && \
    echo "deb mirror://mirrors.ubuntu.com/mirrors.txt $(. /etc/os-release && echo $VERSION_CODENAME)-security main restricted universe multiverse" >> /etc/apt/sources.list

# Install musl & remove the apt-get cache again
RUN apt-get update && apt-get install -y perl wget make musl-tools musl-dev && rm -rf /var/lib/apt/lists/*

# Copy the build script
COPY ./contrib/scripts/container-build.sh /build.sh
RUN chmod +x /build.sh

# Create the build directory
RUN mkdir /build

# Run the build script
ENTRYPOINT [ "/build.sh" ]
