# Define final image
FROM ubuntu:20.04
LABEL org.opencontainers.image.source https://github.com/onnovalkering/brane

# Install the package dependencies
RUN apt-get update && apt-get install -y \
    libssl1.1 \
 && rm -rf /var/lib/apt/lists/*

# Copy the build script
COPY ./start.sh start.sh
RUN chmod +x start.sh

# Create the build directory
RUN mkdir /build

# Run the build script
ENTRYPOINT [ "/start.sh", "brane-drv" ]
